[package]
name = "windows-bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs" }
# windows = "0.19"

[build-dependencies]
windows = { git = "https://github.com/microsoft/windows-rs" }
# windows = "0.19"
